version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
      - cache
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DB_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - CACHE_CONNECTION_STRING=redis://${REDIS_HOST}:${REDIS_PORT}

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}

  cache:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
